// Generated by @ui-kit/core's buildThemeDeclarationModule — do not edit by hand.
import type { Theme } from "./theme";

declare module "styled-components" {
  export interface DefaultTheme extends Theme {}
}
