// Generated by @ui-kit/core's buildThemeDecoratorModule — do not edit by hand.
import { ThemeProvider } from "../src/providers/ThemeProvider/ThemeProvider";
import { preferredTheme } from "./brandTheme";

// Docs pages follow the branded Storybook theme.
export const parameters = { docs: { theme: preferredTheme } };

export default function ThemeDecorator(Story: () => React.ReactNode) {
  return <ThemeProvider>{Story()}</ThemeProvider>;
}
