// Generated by @ui-kit/core's buildThemeDecoratorModule — do not edit by hand.
import { ThemeProvider } from "../src/providers/ThemeProvider/ThemeProvider";

export default function ThemeDecorator(Story: () => React.ReactNode) {
  return <ThemeProvider>{Story()}</ThemeProvider>;
}
